### PR TITLE
Remove Ruby 1.9.3 from deploy-time testing

### PR DESCRIPTION
**Pull request by eheydrick**
#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)
What's in Unreleased covers this change

- [x] Existing tests pass

#### Purpose

Ruby 1.9.3 is no longer supported so no need for deploy-time testing.

### CODE REVIEW

**Comment by majormoses** [comment]
you need to fix up the gem name here: https://github.com/sensu-plugins/sensu-plugins-trafficserver/pull/1/files#diff-354f30a63fb0907d4ad57269548329e3R21

**Comment by majormoses** [comment]
In case it was not clear what I meant, the name of the gem does not match the name of the file: https://github.com/sensu-plugins/sensu-plugins-trafficserver/blob/0.0.2/sensu-plugins-trafficserver.gemspec#L30

**Comment by eheydrick** [comment]
Ah yes, I'll fix that up. One of the oddly named plugins.

**Comment by eheydrick** [comment]
Fixed name, build succeeds now.

**Review by majormoses — APPROVED** [review]
LGTM

**Pull request merged**
